name: DevInHouse-Triggers

on:
  push:

jobs:
  new-comment:
    runs-on:  ubuntu-latest
    steps:
      - name: Get issue id
        run: curl 'https://api.github.com/repos/DevVitorPedra/GH-actions/issues'
